networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      #- pgsql
    networks:
      - laravel

#  pgsql:
#    image: postgres
#    container_name: pgsql
#    environment:
#      POSTGRES_USER: rotativeline
#      POSTGRES_PASSWORD: rotativeline
#      POSTGRES_DB: public
#    volumes:
#      - ./pgsql:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - ./src:/var/www/html
    environment:
      COMPOSER_FUND: 0
    #command: sh -c "composer update --ignore-platform-reqs && composer install --ignore-platform-reqs && tail -F anything"
    networks:
      - laravel